### ISSUE TITLE
Bridge container restarts: RSV1 must be clear

### ISSUE THREAD

**Issue by sebohe** [WalletConnect/node-walletconnect-bridge#51]
This error: `RangeError: Invalid WebSocket frame: RSV1 must be clear`

Is causing the node container to restart every now and then. We can see the performance impacts with this graph:
![image](https://user-images.githubusercontent.com/10123236/95722650-801c2580-0c74-11eb-8311-36cf91f46046.png)

The current solution would be to just handle the error to avoid crashing the process.

Steps:

- [x] Obtain more context from logs of nginx, node, and docker to be able to reproduce the crash.
- [x]  Reproduce the error and write code to catch the error.

**Comment by sebohe** [comment]
The errors that were collected from the bridge containers was the following: 

```
RangeError: Invalid WebSocket frame: invalid payload length 126
    at Receiver.getInfo (/root/node_modules/ws/lib/receiver.js:217:16)
    at Receiver.startLoop (/root/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/root/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/root/node_modules/ws/lib/websocket.js:872:35)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
    at Receiver.receiverOnError (/root/node_modules/ws/lib/websocket.js:777:13)
    at Receiver.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at Receiver.startLoop (/root/node_modules/ws/lib/receiver.js:152:5)
    at Receiver._write (/root/node_modules/ws/lib/receiver.js:78:10)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

A proposed solution to handle it is here: https://github.com/WalletConnect/node-walletconnect-bridge/pull/52/files


The error was reproduced with the following script:

```javascript
const WebSocket = require("ws");

const ws = new WebSocket("ws://localhost:5001");

ws.on("open", function() {
  ws._socket.write(Buffer.from([0x89, 0xfe]));
  process.exit();
});
```

**Comment by sebohe** [comment]
Solved with PR: https://github.com/WalletConnect/node-walletconnect-bridge/pull/52
